# Generated by Django 4.0.2 on 2022-03-25 05:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRecord',
            fields=[
                ('house_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='House Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('date_accomplished', models.DateTimeField(verbose_name='Date Accomplished')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('family_name', models.CharField(max_length=100, verbose_name='Family Name')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
            ],
            options={
                'verbose_name': 'house record',
                'verbose_name_plural': 'house records',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('family_member_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Family Member ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(130)], verbose_name='Age')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Birth Place')),
                ('citizenship', models.CharField(max_length=255, verbose_name='Citizenship')),
                ('civil_status', models.CharField(choices=[('SI', 'Single'), ('MD', 'Married'), ('WD', 'Widowed'), ('SP', 'Separated'), ('DV', 'Divorced'), ('CH', 'Cohabiting')], default='SI', max_length=2, verbose_name='Civil Status')),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
                ('extension', models.CharField(max_length=255, verbose_name='Extension')),
                ('monthly_income', models.PositiveIntegerField(verbose_name='Monthly Income')),
                ('remarks', models.CharField(max_length=255, verbose_name='Remarks')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('O', 'Others')], max_length=1, verbose_name='Gender`')),
                ('house_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbi.houserecord', verbose_name='House Number')),
            ],
            options={
                'verbose_name': 'family member',
                'verbose_name_plural': 'family members',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
