# Generated by Django 4.0.2 on 2022-02-14 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Name of Recipient')),
                ('purpose', models.TextField(blank=True, max_length=500, verbose_name='Purpose')),
                ('government_id', models.ImageField(upload_to='appointment/government_id', verbose_name='Government I.D.')),
                ('start_appointment', models.DateTimeField(verbose_name='Start Appointment')),
                ('end_appointment', models.DateTimeField(blank=True, null=True, verbose_name='End Appointment')),
                ('document', models.CharField(choices=[('IND', 'Indigency'), ('VER', 'Verification'), ('EMP', 'Local Employment'), ('CLP', 'Clearance Permit'), ('CFA', 'Certificate to File Action'), ('COF', 'Complaint Filing'), ('CFC', 'Certificate to File Counterclaim'), ('BOR', 'Borrowing of Tools and Equipment'), ('APT', 'General Appointment')], max_length=3, verbose_name='Document')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('APP', 'Completed'), ('CAN', 'Cancelled'), ('REJ', 'Rejected'), ('APP', 'Approved')], default='PEN', max_length=3, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['created_at'],
            },
        ),
    ]
