# Generated by Django 4.0.2 on 2022-02-14 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    replaces = [('announcement', '0001_initial'), ('announcement', '0002_alter_announcement_options_announcement_slug_and_more'), ('announcement', '0003_rename_featured_announcement_is_featured_and_more'), ('announcement', '0004_remove_announcement_author_and_more'), ('announcement', '0005_announcement_author'), ('announcement', '0006_announcement_username_alter_announcement_author'), ('announcement', '0007_alter_announcement_slug'), ('announcement', '0008_alter_announcement_options'), ('announcement', '0009_remove_announcement_username')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(default='announcement/thumbnail/default.jpg', upload_to='announcement/thumbnail')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
            },
        ),
    ]
