# Generated by Django 4.0.2 on 2022-02-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0002_alter_announcement_options_announcement_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="featured",
            new_name="is_featured",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="Title"),
        ),
    ]
