# Generated by Django 4.0.2 on 2022-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0006_announcement_username_alter_announcement_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
