# Generated by Django 4.0.2 on 2022-02-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_alter_announcement_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'announcement', 'verbose_name_plural': 'announcements'},
        ),
    ]
