# Generated by Django 4.0.2 on 2022-02-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_alter_announcement_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='username',
        ),
    ]
