# Generated by Django 4.0.2 on 2022-02-01 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_profile_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Widowed", "Widowed"),
                    ("Separated", "Separated"),
                    ("Divorced", "Divorced"),
                    ("Annulled", "Annulled"),
                    ("Cohabiting", "Cohabiting"),
                ],
                default="Single",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
