# Generated by Django 4.0.2 on 2022-02-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
