# Generated by Django 4.0.2 on 2022-02-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_speaker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Speaker",
        ),
    ]
