# Generated by Django 4.0.2 on 2022-02-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
