# Generated by Django 4.0.2 on 2022-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_profile_address_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
